### PR TITLE
Adding read-only realm support.

### PR DESCRIPTION
**Pull request by narciero**
Very small change made to RealmSearchViewController that allows for the use of read-only realms. Added ReadOnlyBlogSearchViewController to the Example project for testing. Just change the class of the ViewController in Main.storyboard for quick testing between the two.

### CODE REVIEW

**Comment by bigfish24** [comment]
Looks great, can you make sure similar changes are in the objective-c version as well?

**Comment by narciero** [comment]
Added ObjC support...let me know what you think. I think I covered everything.

**Comment by narciero** [comment]
eta on merge? dont mean to rush, i know you're busy...just wondering b/c i have deadline for project using this library and just wanna know if i should create my own pod from the fork for now. Thanks!

**Comment by bigfish24** [comment]
@narciero sorry for slow reply, was traveling!

**Comment by bigfish24** [comment]
👍

**Pull request merged**
